services:
  db:
    image: postgres:15
    container_name: crewai_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crewaiuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret123}
      POSTGRES_DB: ${POSTGRES_DB:-crewai}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: crewai_studio
    depends_on:
      - db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-}
      OPENAI_PROXY_MODELS: ${OPENAI_PROXY_MODELS:-}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      LMSTUDIO_API_BASE: ${LMSTUDIO_API_BASE:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      AGENTOPS_API_KEY: ${AGENTOPS_API_KEY:-}
      AGENTOPS_ENABLED: ${AGENTOPS_ENABLED:-False}
      OLLAMA_HOST: ${OLLAMA_HOST:-}
      OLLAMA_MODELS: ${OLLAMA_MODELS:-}
      SERPER_API_KEY: ${SERPER_API_KEY:-}
      DB_URL: postgresql://${POSTGRES_USER:-crewaiuser}:${POSTGRES_PASSWORD:-secret123}@db:5432/${POSTGRES_DB:-crewai}
    ports:
      - "${WEB_PORT:-8501}:8501"
    restart: always

volumes:
  db-data:
